version: '3'

services:

  php:
    build:
      context: ./php/8.1-nginx-slim/
      dockerfile: ./php/8.1-nginx-slim/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - php

networks:
  php:
    driver: bridge
