name: Docker CI

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

  # Run tests for any PRs.
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push to registry
        run: make release-all
