name: Docker CI

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

  # Run tests for any PRs.
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags.

      - name: Login into registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${GITHUB_TOKEN}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push to registry
        run: make release-all
