name: Docker CI

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

  # Run tests for any PRs.
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login into registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: bash build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
